name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
version: "${project.version}"
api-version: "${project.api-version}"
author: "${project.developers[0].name}"
description: "${project.description}"
depend:
  - "GriefPrevention"

permissions:
  givepet.give:
    default: true
  givepet.receive:
    default: true

commands:
  givepet:
    aliases: [ "transferpet" ]
    description: "Give someone a tamed animal of yours!"
    permission: "givepet.give"
    usage: "/<command> <player>"
  acceptpet:
    description: "Accept a gifted pet!"
    permission: "givepet.receive"
    usage: "/<command>"
  declinepet:
    description: "Decline a gifted pet."
    permission: "givepet.receive"
    usage: "/<command>"